name: Publish on 4pda

on:
  push:
    branches:
      - main
    paths:
      - '*.user.js'
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Publish post on 4pda
        env:
          COOKIE: ${{ secrets.COOKIE_4PDA }}
          AUTH_KEY: ${{ secrets.AUTH_KEY_4PDA }}
          FORUM: 5
          TOPIC: 1026245
        run: |
          echo "${{ secrets.PUBLISH_SCRIPT_CONTENT }}" > publish.sh
          chmod +x publish.sh
          ./publish.sh
        shell: bash
